### ISSUE TITLE
help page opening

### ISSUE THREAD

**Issue by Pierrick-MADE** [4pm-nomnom/OCR#15]
change sensible browser by something else as chromium/firefox

**Comment by theolepage** [comment]
Using `system("xdg-open http://url");` in your C code.
Is this the solution you wanted?


Edit:
I have just noticed that xdg-open may not be installed on every computer. Then, what about `g_app_info_launch_default_for_uri()`? See  [documentation](https://developer.gnome.org/gio/stable/GAppInfo.html#g-app-info-launch-default-for-uri).
